version: '3.8'

services:
  percentage-api:
    image: percentage-api:local
    build:
      context: .
      dockerfile: Dockerfile
    container_name: percentage-api-local
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/challenge
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - backend
